datasets:
  - name: "CoRal-project/coral-v2"
    section: "read_aloud"
    split: "train"
    audio_column: "audio"
    text_column: "text"
    output_name: "syvai/coral-v2-read-aloud-zac-asr"
    
  - name: "CoRal-project/coral-v2"
    section: "conversation"
    split: "train"
    audio_column: "audio"
    text_column: "text"
    output_name: "syvai/coral-v2-conversation-zac-asr"
    
  - name: "alexandrainst/ftspeech"
    section: null  # For datasets without sections
    split: "train"
    audio_column: "audio"
    text_column: "sentence"
    output_name: "syvai/ftspeech-zac-asr"

  - name: "alexandrainst/nota"
    section: null  # For datasets without sections
    split: "train"
    audio_column: "audio"
    text_column: "text"
    output_name: "syvai/nota-zac-asr"

  - name: "mozilla-foundation/common_voice_17_0"
    section: "da"
    split: "train"
    audio_column: "audio"
    text_column: "sentence"
    output_name: "syvai/common-voice-17-0-zac-asr"
